# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 455)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, 7, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 12, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_edit.sizePolicy().hasHeightForWidth())
        self.path_edit.setSizePolicy(sizePolicy)
        self.path_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.path_edit.setObjectName("path_edit")
        self.horizontalLayout.addWidget(self.path_edit)
        self.browse_button = QtWidgets.QToolButton(self.centralwidget)
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout.addWidget(self.browse_button)
        self.paste_button = QtWidgets.QPushButton(self.centralwidget)
        self.paste_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("asset/iconfinder_Paste_27862(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.paste_button.setIcon(icon)
        self.paste_button.setObjectName("paste_button")
        self.horizontalLayout.addWidget(self.paste_button)
        self.preview_button = QtWidgets.QPushButton(self.centralwidget)
        self.preview_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_button.sizePolicy().hasHeightForWidth())
        self.preview_button.setSizePolicy(sizePolicy)
        self.preview_button.setMinimumSize(QtCore.QSize(0, 0))
        self.preview_button.setObjectName("preview_button")
        self.horizontalLayout.addWidget(self.preview_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.preview_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preview_label.sizePolicy().hasHeightForWidth())
        self.preview_label.setSizePolicy(sizePolicy)
        self.preview_label.setText("")
        self.preview_label.setAlignment(QtCore.Qt.AlignCenter)
        self.preview_label.setObjectName("preview_label")
        self.verticalLayout.addWidget(self.preview_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prev_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_button.sizePolicy().hasHeightForWidth())
        self.prev_button.setSizePolicy(sizePolicy)
        self.prev_button.setObjectName("prev_button")
        self.horizontalLayout_2.addWidget(self.prev_button)
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_button.sizePolicy().hasHeightForWidth())
        self.next_button.setSizePolicy(sizePolicy)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_2.addWidget(self.next_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_17.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(10, 0))
        self.line.setStyleSheet("")
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout_17.addWidget(self.line)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.translate_comboBox = QtWidgets.QComboBox(self.widget)
        self.translate_comboBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translate_comboBox.sizePolicy().hasHeightForWidth())
        self.translate_comboBox.setSizePolicy(sizePolicy)
        self.translate_comboBox.setMaxCount(110)
        self.translate_comboBox.setObjectName("translate_comboBox")
        self.translate_comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.translate_comboBox)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout_17.addWidget(self.widget)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.speed_comboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed_comboBox.sizePolicy().hasHeightForWidth())
        self.speed_comboBox.setSizePolicy(sizePolicy)
        self.speed_comboBox.setEditable(False)
        self.speed_comboBox.setMaxVisibleItems(8)
        self.speed_comboBox.setMaxCount(10)
        self.speed_comboBox.setMinimumContentsLength(0)
        self.speed_comboBox.setObjectName("speed_comboBox")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.horizontalLayout_18.addWidget(self.speed_comboBox)
        self.play_pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_pause_button.setStatusTip("")
        self.play_pause_button.setText("")
        self.play_pause_button.setObjectName("play_pause_button")
        self.horizontalLayout_18.addWidget(self.play_pause_button)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setText("")
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_18.addWidget(self.stop_button)
        self.volume_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volume_slider.sizePolicy().hasHeightForWidth())
        self.volume_slider.setSizePolicy(sizePolicy)
        self.volume_slider.setMaximum(100)
        self.volume_slider.setProperty("value", 60)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.horizontalLayout_18.addWidget(self.volume_slider)
        self.position = QtWidgets.QLabel(self.centralwidget)
        self.position.setObjectName("position")
        self.horizontalLayout_18.addWidget(self.position)
        self.radio_seek_slider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_seek_slider.sizePolicy().hasHeightForWidth())
        self.radio_seek_slider.setSizePolicy(sizePolicy)
        self.radio_seek_slider.setStatusTip("")
        self.radio_seek_slider.setMaximum(100)
        self.radio_seek_slider.setOrientation(QtCore.Qt.Horizontal)
        self.radio_seek_slider.setObjectName("radio_seek_slider")
        self.horizontalLayout_18.addWidget(self.radio_seek_slider)
        self.duration = QtWidgets.QLabel(self.centralwidget)
        self.duration.setObjectName("duration")
        self.horizontalLayout_18.addWidget(self.duration)
        self.verticalLayout_13.addLayout(self.horizontalLayout_18)
        self.verticalLayout_3.addLayout(self.verticalLayout_13)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 20))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuExport = QtWidgets.QMenu(self.menubar)
        self.menuExport.setObjectName("menuExport")
        self.menuPrefrence = QtWidgets.QMenu(self.menubar)
        self.menuPrefrence.setObjectName("menuPrefrence")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.export_txt = QtWidgets.QAction(MainWindow)
        self.export_txt.setEnabled(False)
        self.export_txt.setObjectName("export_txt")
        self.actionPDFF = QtWidgets.QAction(MainWindow)
        self.actionPDFF.setObjectName("actionPDFF")
        self.export_pdf = QtWidgets.QAction(MainWindow)
        self.export_pdf.setEnabled(False)
        self.export_pdf.setObjectName("export_pdf")
        self.export_mp3 = QtWidgets.QAction(MainWindow)
        self.export_mp3.setEnabled(False)
        self.export_mp3.setObjectName("export_mp3")
        self.actionDark_Mode = QtWidgets.QAction(MainWindow)
        self.actionDark_Mode.setObjectName("actionDark_Mode")
        self.actionLight_Mode = QtWidgets.QAction(MainWindow)
        self.actionLight_Mode.setObjectName("actionLight_Mode")
        self.menuFIle.addAction(self.actionOpen)
        self.menuFIle.addAction(self.actionSave)
        self.menuFIle.addAction(self.actionExit)
        self.menuExport.addAction(self.export_txt)
        self.menuExport.addAction(self.export_pdf)
        self.menuExport.addAction(self.export_mp3)
        self.menuPrefrence.addAction(self.actionDark_Mode)
        self.menuPrefrence.addAction(self.actionLight_Mode)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuPrefrence.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.speed_comboBox.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.path_edit.setPlaceholderText(_translate("MainWindow", "Paste URL / Browse file (Img, Txt, PDF)"))
        self.browse_button.setText(_translate("MainWindow", "..."))
        self.preview_button.setText(_translate("MainWindow", "Go"))
        self.prev_button.setText(_translate("MainWindow", "prev"))
        self.next_button.setText(_translate("MainWindow", "next"))
        self.translate_comboBox.setItemText(0, _translate("MainWindow", "Select Language"))
        self.pushButton.setToolTip(_translate("MainWindow", "Buy me a Coffee"))
        self.speed_comboBox.setToolTip(_translate("MainWindow", "Playback Speed"))
        self.speed_comboBox.setWhatsThis(_translate("MainWindow", "Playback Speed"))
        self.speed_comboBox.setCurrentText(_translate("MainWindow", "1.0x"))
        self.speed_comboBox.setItemText(0, _translate("MainWindow", "0.25x"))
        self.speed_comboBox.setItemText(1, _translate("MainWindow", "0.5x"))
        self.speed_comboBox.setItemText(2, _translate("MainWindow", "0.75x"))
        self.speed_comboBox.setItemText(3, _translate("MainWindow", "1.0x"))
        self.speed_comboBox.setItemText(4, _translate("MainWindow", "1.25x"))
        self.speed_comboBox.setItemText(5, _translate("MainWindow", "1.5x"))
        self.speed_comboBox.setItemText(6, _translate("MainWindow", "1.75x"))
        self.speed_comboBox.setItemText(7, _translate("MainWindow", "2x"))
        self.play_pause_button.setToolTip(_translate("MainWindow", "Play/Pause"))
        self.position.setText(_translate("MainWindow", "00:00:00"))
        self.radio_seek_slider.setToolTip(_translate("MainWindow", "Seek"))
        self.duration.setText(_translate("MainWindow", "00:00:00"))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuPrefrence.setTitle(_translate("MainWindow", "Prefrence"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.export_txt.setText(_translate("MainWindow", "Plain Text"))
        self.actionPDFF.setText(_translate("MainWindow", "PDF"))
        self.export_pdf.setText(_translate("MainWindow", "PDF"))
        self.export_mp3.setText(_translate("MainWindow", "Audio"))
        self.actionDark_Mode.setText(_translate("MainWindow", "Dark Mode"))
        self.actionLight_Mode.setText(_translate("MainWindow", "Light Mode"))
